spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/joboffers
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

job-offers:
  offer-fetcher:
    scheduler:
      delay: PT3H
    http:
      client:
        config:
          connectionTimeout: 1000
          readTimeout: 1000
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 5057

scheduling:
  enabled: true
